# Generated by Django 4.2.5 on 2023-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='null', max_length=100, verbose_name='Город'),
        ),
    ]
