# Generated by Django 4.2.5 on 2023-10-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('price', models.CharField(max_length=255, verbose_name='Примерная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
