# Generated by Django 4.2.5 on 2023-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0005_catalog_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
