# Generated by Django 4.2.5 on 2023-11-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0006_alter_catalog_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('members_count', models.CharField(max_length=255, verbose_name='Количество участников')),
                ('is_joined', models.BooleanField(default=False, verbose_name='Вступил')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Список сообществ',
            },
        ),
    ]
