# Generated by Django 4.2.5 on 2023-11-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0008_alter_catalog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория на обмен',
                'verbose_name_plural': 'Категории на обмен',
            },
        ),
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.category_exchange', verbose_name='Категория товара на обмен'),
        ),
    ]
