# Generated by Django 4.2.5 on 2023-12-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0012_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='category_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_exchange', to='fastbarterApp.category', verbose_name='Категория товара на обмен'),
        ),
    ]
