# Generated by Django 4.2.5 on 2023-12-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0013_alter_catalog_category_exchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_exchange',
        ),
    ]
