# Generated by Django 4.2.5 on 2023-12-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0015_alter_reviews_options_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='user1',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user2',
        ),
    ]
