# Generated by Django 4.2.5 on 2023-12-01 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastbarterApp', '0017_alter_chats_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='user',
        ),
        migrations.AddField(
            model_name='chats',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2'),
        ),
    ]
