# Generated by Django 4.2.5 on 2023-12-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0019_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='members_count',
        ),
    ]
