# Generated by Django 4.2.5 on 2023-12-06 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastbarterApp', '0020_remove_groups_is_joined_remove_groups_members_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
