# Generated by Django 4.2.5 on 2023-12-09 04:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0022_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to='files/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.CharField(default=0, max_length=255, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='', max_length=255, verbose_name='Отзыв'),
        ),
    ]
