# Generated by Django 4.2.5 on 2023-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0023_reviews_created_at_reviews_file_reviews_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to='files/', verbose_name='Файл'),
        ),
    ]
