# Generated by Django 4.2.5 on 2023-12-11 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastbarterApp', '0026_alter_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='userTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому оставили отзыв'),
        ),
    ]
