# Generated by Django 4.2.5 on 2023-12-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0029_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
