# Generated by Django 4.2.16 on 2024-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0030_deals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to='files/', verbose_name='Файл'),
        ),
    ]
