# Generated by Django 4.2.16 on 2024-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0031_chats_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='file',
        ),
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to='files/', verbose_name='Файл'),
        ),
    ]
