# Generated by Django 4.2.16 on 2024-10-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0032_remove_chats_file_messages_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='catalog2',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user2',
        ),
        migrations.AddField(
            model_name='chats',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.deals', verbose_name='Сделка'),
        ),
    ]
