# Generated by Django 4.2.16 on 2024-10-13 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fastbarterApp', '0034_chats_is_deleted_user1_chats_is_deleted_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='is_deleted_user1',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='is_deleted_user2',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='catalog2',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='user2',
        ),
        migrations.AddField(
            model_name='chats',
            name='is_deleted_user_customer',
            field=models.BooleanField(default=False, verbose_name='Удален у пользователя, предложившего обмен'),
        ),
        migrations.AddField(
            model_name='chats',
            name='is_deleted_user_owner',
            field=models.BooleanField(default=False, verbose_name='Удален у пользователя-владельца объявления'),
        ),
        migrations.AddField(
            model_name='deals',
            name='catalog_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_customer', to='fastbarterApp.catalog', verbose_name='Товар пользователя, предложившего обмен'),
        ),
        migrations.AddField(
            model_name='deals',
            name='catalog_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.catalog', verbose_name='Товар владельца объявления'),
        ),
        migrations.AddField(
            model_name='deals',
            name='user_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, предложивший обмен'),
        ),
        migrations.AddField(
            model_name='deals',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-владелец объявления'),
        ),
    ]
