# Generated by Django 4.2.16 on 2024-10-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0036_rename_catalog_owner_deals_owner_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='customer_product',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='owner_product',
        ),
        migrations.AddField(
            model_name='deals',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog2', to='fastbarterApp.catalog', verbose_name='Товар пользователя, предложившего обмен'),
        ),
    ]
