# Generated by Django 4.2.16 on 2024-11-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastbarterApp', '0040_alter_catalog_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок записи')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Текст')),
                ('file', models.FileField(blank=True, default=False, null=True, upload_to='files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fastbarterApp.groups', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Запись сообщества',
                'verbose_name_plural': 'Записи сообществ',
            },
        ),
    ]
